# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chat_request_response_pb2 as chat__request__response__pb2


class chatmanageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ping = channel.unary_stream(
            "/chatmanagement.chatmanage/ping",
            request_serializer=chat__request__response__pb2.sendtext.SerializeToString,
            response_deserializer=chat__request__response__pb2.receiveacknowledgment.FromString,
        )
        self.lastseen = channel.unary_unary(
            "/chatmanagement.chatmanage/lastseen",
            request_serializer=chat__request__response__pb2.checkonlinestatus.SerializeToString,
            response_deserializer=chat__request__response__pb2.receivestatus.FromString,
        )


class chatmanageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def lastseen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_chatmanageServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ping": grpc.unary_stream_rpc_method_handler(
            servicer.ping,
            request_deserializer=chat__request__response__pb2.sendtext.FromString,
            response_serializer=chat__request__response__pb2.receiveacknowledgment.SerializeToString,
        ),
        "lastseen": grpc.unary_unary_rpc_method_handler(
            servicer.lastseen,
            request_deserializer=chat__request__response__pb2.checkonlinestatus.FromString,
            response_serializer=chat__request__response__pb2.receivestatus.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "chatmanagement.chatmanage", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class chatmanage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ping(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/chatmanagement.chatmanage/ping",
            chat__request__response__pb2.sendtext.SerializeToString,
            chat__request__response__pb2.receiveacknowledgment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def lastseen(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chatmanagement.chatmanage/lastseen",
            chat__request__response__pb2.checkonlinestatus.SerializeToString,
            chat__request__response__pb2.receivestatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
