# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat_request_response.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1b\x63hat_request_response.proto\x12\x0e\x63hatmanagement"\\\n\x08sendtext\x12\x12\n\nsenders_id\x18\x01 \x01(\t\x12\x14\n\x0creceivers_id\x18\x02 \x01(\t\x12\x16\n\x0emessage_update\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t"@\n\x15receiveacknowledgment\x12\x16\n\x0emessage_status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t"=\n\x11\x63heckonlinestatus\x12\x12\n\nsenders_id\x18\x01 \x01(\t\x12\x14\n\x0creceivers_id\x18\x02 \x01(\t"!\n\rreceivestatus\x12\x10\n\x08lastseen\x18\x01 \x01(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "chat_request_response_pb2", _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_SENDTEXT"]._serialized_start = 47
    _globals["_SENDTEXT"]._serialized_end = 139
    _globals["_RECEIVEACKNOWLEDGMENT"]._serialized_start = 141
    _globals["_RECEIVEACKNOWLEDGMENT"]._serialized_end = 205
    _globals["_CHECKONLINESTATUS"]._serialized_start = 207
    _globals["_CHECKONLINESTATUS"]._serialized_end = 268
    _globals["_RECEIVESTATUS"]._serialized_start = 270
    _globals["_RECEIVESTATUS"]._serialized_end = 303
# @@protoc_insertion_point(module_scope)
