# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatting_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import chat_request_response_pb2 as chat__request__response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16\x63hatting_service.proto\x12\x0e\x63hatmanagement\x1a\x1b\x63hat_request_response.proto2\xa9\x01\n\nchatmanage\x12K\n\x04ping\x12\x18.chatmanagement.sendtext\x1a%.chatmanagement.receiveacknowledgment"\x00\x30\x01\x12N\n\x08lastseen\x12!.chatmanagement.checkonlinestatus\x1a\x1d.chatmanagement.receivestatus"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "chatting_service_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_CHATMANAGE"]._serialized_start = 72
    _globals["_CHATMANAGE"]._serialized_end = 241
# @@protoc_insertion_point(module_scope)
